spring:
  data:
    mongodb:
      uri: mongodb+srv://JournalUser:zwPNNb1BExUJzsmF@cluster0.lrpe6q1.mongodb.net/journaldb?retryWrites=true&w=majority
      name: Journal_App
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /app